FROM rust:alpine3.18 as base

RUN /bin/sh -c apk add --no-cache libpq
RUN cargo build --release -p quicklook-rs -p cli

COPY target/release/quicklook-rs /usr/local/bin/quicklook-rs
COPY target/release/cli /usr/local/bin/quicklook-cli

EXPOSE 3030

CMD ["quicklook-rs"]
