services:
  quicklook-server:
    image: cangzhang/quicklook-rs:nightly-a9fd140
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:testpassword@db:5432/quicklook
      PORT: 3030
    ports:
      - "3333:3030"
    depends_on:
      - db

  # Postgres
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5243:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
