services:
  quicklook-server:
    image: cangzhang/quicklook-rs:nightly-a9fd140
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:testpassword@db:5243/quicklook
      PORT: 3030
    ports:
      - "3030:3030"
    depends_on:
      - db
