services:
  quicklook-server:
    image: cangzhang/quicklook-rs:nightly-a9fd140
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:testpassword@db:5432/quicklook
      PORT: 3030
    ports:
      - "3333:3030"
    depends_on:
      - db
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sync-build.schedule: "0 0 5 * * *"
      ofelia.job-exec.sync-build.command: "/usr/local/bin/quicklook-cli sync-build"
      ofelia.job-exec.sync-source.schedule: "0 0 0,12 * * *"
      ofelia.job-exec.sync-source.command: "/usr/local/bin/quicklook-cli sync-source"

  # Postgres
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5243:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - app
    restart: "always"
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db:
    driver: local
